### ISSUE TITLE
Visual Studio 2013 ICE with Entity::unpack()

### ISSUE THREAD

**Issue by Klaim** [alecthomas/entityx#105]
Both test and usage of Entity::unpack() trigger an ICE when I try to compile EntityX or it's tests:

1>E:\Projects\TBR\build-tbr-vs2012-32\EntityX_proj-prefix\src\EntityX_proj\entityx\Entity_test.cc(267): fatal error C1001: An internal error has occurred in the compiler. [E:\Projects\TBR\build-tbr-vs2012-32\EntityX_proj-prefix\src\EntityX_proj-build\entity_test.vcxproj]

This is with v1.1.2 and current master.

**Comment by alecthomas** [comment]
Yes, it seems you need at least 2014 to use EntityX. I'm not sure if this was always the case, but AppVeyor (the VC++ CI) uses 2014 and passes fine.

**Comment by Klaim** [comment]
Yes I did try VS2015 RC (vc14 compiler, there is no VS2014)  first and there is no problem.
I tried VS2013 once I read in the readme that it should compile with it too.
Maybe you should just update the ReadMe then?
See https://github.com/alecthomas/entityx#installation

**Comment by alecthomas** [comment]
I'm pretty sure it used to work on 2013, but it's possible that either a subsequent change to EntityX broke the compiler, or a subsequent patch to the compiler broke support. I don't have access to a Windows machine, but if you have the time it would be interesting to do a git bisect and find out which commit causes the ICE. I understand if that's too much effort though.

Thanks for the report.

**Comment by teisnet** [comment]
It seems that the two VS 2013 compiler errors are introduced by commit https://github.com/alecthomas/entityx/commit/29d8c3763c27e5cc18695f8261145c836670efd7

The two errors are "error C1001: An internal error has occurred in the compiler." triggered in [Entity_test.cc, line 267](https://github.com/alecthomas/entityx/blob/master/entityx/Entity_test.cc#L267) and [System_test.cc, line 65](https://github.com/alecthomas/entityx/blob/1.2.0/entityx/System_test.cc#L65).

**Comment by teisnet** [comment]
Could it be related to Entity::unpack<>() being called with only one template argument?

**Comment by alecthomas** [comment]
My guess is it is related to the SFINAE changes. IIRC VS2013 was quite
buggy.

If that is the case it will be difficult to fix. VS2015 works fine if
that's an option.
